# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/myosotis/yocto-stm32-labs/poky/meta \
  /home/myosotis/yocto-stm32-labs/poky/meta-poky \
  /home/myosotis/yocto-stm32-labs/poky/meta-yocto-bsp \
  /home/myosotis/yocto-stm32-labs/meta-openembedded/meta-oe \
  /home/myosotis/yocto-stm32-labs/meta-openembedded/meta-python \
  /home/myosotis/yocto-stm32-labs/meta-st-stm32mp \
  /home/myosotis/yocto-stm32-labs/meta-bootlinlabs \
  "
